import pytest

from pgllens.config import Settings
from pgllens.database.format import QueryResult
from pgllens.database.introspect import Introspector, TableNotFoundError

DSN = "postgresql://u:p@localhost:5432/flux"


class FakeDb:
    """Replays canned QueryResults in call order and counts round trips."""

    def __init__(self, results):
        self._results = list(results)
        self.calls = 0
        self.seen: list[tuple] = []

    async def run_system(self, sql, params=(), max_rows=None):
        self.calls += 1
        self.seen.append((sql, params, max_rows))
        return self._results.pop(0) if self._results else QueryResult([], [], False)


TABLES = QueryResult(
    columns=["table_schema", "table_name", "table_kind", "table_comment", "row_estimate"],
    rows=[("wms", "item_master", "r", "Items", 1200),
          ("wms", "inventory_position", "r", None, 98000)],
    truncated=False,
)
COLUMNS = QueryResult(
    columns=["table_schema", "table_name", "column_name", "data_type",
             "is_nullable", "column_default", "column_comment", "ordinal_position",
             "type_schema", "is_identity"],
    # is_nullable mirrors the real wire shape: information_schema.columns.is_nullable
    # is the text 'YES'/'NO', never a Python bool. is_identity is pg_attribute.attidentity:
    # '' (not an identity column), 'a' (GENERATED ALWAYS), 'd' (GENERATED BY DEFAULT).
    rows=[("wms", "item_master", "id", "uuid", "NO", None, None, 1, "pg_catalog", "a"),
          ("wms", "item_master", "sku", "text", "NO", None, "Stock code", 2, "pg_catalog", ""),
          ("wms", "inventory_position", "id", "uuid", "NO", None, None, 1, "pg_catalog", ""),
          ("wms", "inventory_position", "lpn_id", "uuid", "YES", None, None, 2,
           "pg_catalog", "")],
    truncated=False,
)
PKS = QueryResult(
    columns=["table_schema", "table_name", "column_name"],
    rows=[("wms", "item_master", "id")],
    truncated=False,
)
FKS = QueryResult(
    columns=["constraint", "from_schema", "from_table", "from_columns", "from_not_null",
             "to_schema", "to_table", "to_columns"],
    rows=[("fk_inventory_item", "wms", "inventory_position", ["item_id"], [True],
           "wms", "item_master", ["id"]),
          ("fk_composite", "wms", "item_master", ["region", "sku"], [True, False],
           "wms", "ref_sku", ["region_code", "sku_code"])],
    truncated=False,
)


ENUMS = QueryResult(
    columns=["type_schema", "type_name", "labels"],
    rows=[("app_core", "reading_quality", ["good", "bad", "uncertain"]),
          ("app_core", "dup_kind", ["a1", "a2"]),
          ("other", "dup_kind", ["b1", "b2"]),
          # PascalCase: format_type renders this as "App"."Status", with quotes.
          ("App", "Status", ["Open", "Closed"]),
          ("app_core", "ReadingQuality", ["hi", "lo"])],
    truncated=False,
)

_REPLAY = [TABLES, COLUMNS, PKS, FKS, ENUMS]


def _intro(**kw):
    s = Settings(database_url=DSN, exposed_schemas="wms", **kw)
    db = FakeDb(_REPLAY)
    return Introspector(db, s), db


async def test_tables_are_assembled_with_columns_and_pk():
    intro, _ = _intro()
    tables = await intro.tables()
    assert [t.name for t in tables] == ["item_master", "inventory_position"]
    assert [c.name for c in tables[0].columns] == ["id", "sku"]
    assert tables[0].primary_key == ["id"]
    assert tables[0].columns[1].comment == "Stock code"


async def test_identity_column_is_captured_from_attidentity():
    """D1: an identity column's attidentity ('a'/'d') must ride along so
    describe_table can render GENERATED ALWAYS/BY DEFAULT AS IDENTITY instead
    of a blank default (which reads as "you must supply this yourself")."""
    intro, _ = _intro()
    item = await intro.table("item_master")
    by_name = {c.name: c for c in item.columns}
    assert by_name["id"].is_identity == "a"
    assert by_name["sku"].is_identity == ""


async def test_is_nullable_text_maps_to_a_real_bool():
    """Regression: information_schema.columns.is_nullable is the text 'YES'/'NO';
    both are truthy strings, so a naive bool() cast made every column nullable."""
    intro, _ = _intro()
    tables = await intro.tables()
    inventory = next(t for t in tables if t.name == "inventory_position")
    by_name = {c.name: c for c in inventory.columns}
    assert by_name["id"].nullable is False
    assert by_name["lpn_id"].nullable is True


async def test_cache_is_reused_within_the_refresh_interval():
    intro, db = _intro(schema_refresh_interval_ms=300000)
    await intro.tables()
    first = db.calls
    await intro.tables()
    assert db.calls == first, "second call must be served from cache"


async def test_refresh_forces_a_reload_and_reports_the_count():
    intro, db = _intro()
    await intro.tables()
    before = db.calls
    intro._db._results = list(_REPLAY)  # reload the canned replay
    count = await intro.refresh()
    assert db.calls > before
    assert count == 2


async def test_table_lookup_is_case_insensitive():
    intro, _ = _intro()
    assert (await intro.table("ITEM_MASTER")).name == "item_master"


async def test_unknown_table_raises_with_a_suggestion():
    intro, _ = _intro()
    with pytest.raises(TableNotFoundError, match="item_master"):
        await intro.table("item_mastr")


@pytest.fixture
def intro_with_tables():
    """An Introspector whose tables() yields a table named 'technician' in
    schema 'app_core' (and one in 'app_audit', for the schema-scoped-miss
    cases), built the same way _intro() builds its Introspector."""
    tables = QueryResult(
        columns=["table_schema", "table_name", "table_kind", "table_comment",
                 "row_estimate"],
        rows=[("app_core", "technician", "r", None, 10),
              ("app_audit", "audit_log", "r", None, 500)],
        truncated=False,
    )
    empty_columns = QueryResult(columns=COLUMNS.columns, rows=[], truncated=False)
    empty_pks = QueryResult(columns=PKS.columns, rows=[], truncated=False)
    empty_fks = QueryResult(columns=FKS.columns, rows=[], truncated=False)
    empty_enums = QueryResult(columns=ENUMS.columns, rows=[], truncated=False)
    s = Settings(database_url=DSN, exposed_schemas="app_core,app_audit")
    db = FakeDb([tables, empty_columns, empty_pks, empty_fks, empty_enums])
    return Introspector(db, s)


async def test_table_miss_with_schema_names_the_schema_and_the_real_home(intro_with_tables):
    with pytest.raises(TableNotFoundError) as e:
        await intro_with_tables.table("technician", schema="app_audit")
    msg = str(e.value)
    assert "not found in schema 'app_audit'" in msg
    assert "exists in app_core" in msg
    assert "Did you mean" not in msg


async def test_table_miss_with_schema_and_no_home_still_suggests(intro_with_tables):
    with pytest.raises(TableNotFoundError) as e:
        await intro_with_tables.table("technicain", schema="app_core")
    msg = str(e.value)
    assert "not found in schema 'app_core'" in msg
    assert "Did you mean: technician" in msg


def test_columns_sql_reads_the_real_type_not_information_schema():
    """Regression: information_schema.columns.data_type renders enum columns as
    the literal string 'USER-DEFINED'. format_type(atttypid, atttypmod) on
    pg_attribute (the pattern modules.py::_VIEW_COLUMNS_SQL already uses)
    returns the actual enum type name instead."""
    from pgllens.database.introspect import _COLUMNS_SQL
    assert "format_type(" in _COLUMNS_SQL
    assert "c.data_type" not in _COLUMNS_SQL


def test_columns_sql_selects_attidentity():
    from pgllens.database.introspect import _COLUMNS_SQL
    assert "a.attidentity" in _COLUMNS_SQL


async def test_foreign_keys_preserve_composite_column_pairing():
    intro, _ = _intro()
    fks = await intro.foreign_keys()
    simple = fks[0]
    assert simple.constraint == "fk_inventory_item"
    assert simple.from_columns == ["item_id"]
    assert simple.to_columns == ["id"]
    composite = fks[1]
    assert composite.from_columns == ["region", "sku"]
    assert composite.to_columns == ["region_code", "sku_code"]


async def test_foreign_keys_carry_from_column_not_null():
    """The FK's child/referencing column's NOT NULL (attnotnull) must ride along
    so the ERD mermaid renderer can pick }|--|| vs }o--|| (Task 4)."""
    intro, _ = _intro()
    fks = await intro.foreign_keys()
    simple = fks[0]
    assert simple.from_not_null == [True]
    composite = fks[1]
    assert composite.from_not_null == [True, False]


async def test_foreign_keys_cache_is_reused_within_the_refresh_interval():
    intro, db = _intro(schema_refresh_interval_ms=300000)
    await intro.foreign_keys()
    first = db.calls
    await intro.foreign_keys()
    assert db.calls == first, "second call must be served from cache"


async def test_search_columns_filters_by_substring_case_insensitively():
    intro, _ = _intro()
    assert await intro.search_columns("SKU") == [("wms", "item_master", "sku", "text")]


# --- enum labels (Task 2) ---

QUALITY = ["good", "bad", "uncertain"]


async def test_enum_labels_resolve_qualified_bare_and_array_names():
    intro, _ = _intro()
    assert await intro.enum_labels("app_core.reading_quality") == QUALITY
    assert await intro.enum_labels("reading_quality") == QUALITY
    assert await intro.enum_labels("reading_quality[]") == QUALITY


async def test_ambiguous_bare_enum_name_resolves_only_when_qualified():
    """Two schemas define dup_kind, so the bare key must be omitted rather than
    silently picking one schema's labels."""
    intro, _ = _intro()
    assert await intro.enum_labels("dup_kind") is None
    assert await intro.enum_labels("app_core.dup_kind") == ["a1", "a2"]
    assert await intro.enum_labels("other.dup_kind") == ["b1", "b2"]


async def test_columns_type_schema_disambiguates_a_bare_enum_name():
    """format_type renders `dup_kind` unqualified when its schema is on the
    search_path, so the bare rendering alone is ambiguous -- but the column's
    own type_schema (from pg_type.typnamespace) is not."""
    intro, _ = _intro()
    assert await intro.enum_labels("dup_kind", "app_core") == ["a1", "a2"]
    assert await intro.enum_labels("dup_kind[]", "other") == ["b1", "b2"]
    # An already-qualified rendering is left alone.
    assert await intro.enum_labels("other.dup_kind", "app_core") == ["b1", "b2"]
    # type_schema never turns a non-enum into an enum.
    assert await intro.enum_labels("text", "pg_catalog") is None


async def test_columns_sql_selects_the_types_namespace():
    from pgllens.database.introspect import _COLUMNS_SQL
    assert "tn.nspname AS type_schema" in _COLUMNS_SQL
    intro, _ = _intro()
    t = await intro.table("item_master")
    assert t.columns[0].type_schema == "pg_catalog"


async def test_enum_labels_returns_none_for_a_non_enum_type():
    intro, _ = _intro()
    assert await intro.enum_labels("text") is None


async def test_enum_labels_share_the_schema_cache_round_trip():
    intro, db = _intro(schema_refresh_interval_ms=300000)
    await intro.tables()
    first = db.calls
    await intro.enum_labels("app_core.reading_quality")
    assert db.calls == first, "enum labels must be served from the same cache load"


async def test_a_qualified_non_enum_type_never_borrows_another_schemas_labels():
    """Fix round 1 (Q2): app_core.reading_quality is an enum, other.reading_quality
    could be a domain or composite -- a qualified miss means "not an enum", never
    "fall back to the bare name"."""
    intro, _ = _intro()
    assert await intro.enum_labels("other.reading_quality") is None


async def test_enum_labels_resolve_quoted_identifiers():
    """Fix round 1 (Q3): format_type double-quotes identifiers that need it, but
    the cache keys are the raw nspname/typname."""
    intro, _ = _intro()
    assert await intro.enum_labels('"App"."Status"') == ["Open", "Closed"]
    assert await intro.enum_labels('"ReadingQuality"') == ["hi", "lo"]
    assert await intro.enum_labels('"ReadingQuality"[]') == ["hi", "lo"]


async def test_enums_query_is_not_capped_at_the_default_row_limit():
    """Fix round 1 (Q5): run_system defaults to settings.max_rows (200) and
    truncates silently -- a database with many enums would lose labels."""
    from pgllens.database.introspect import _CATALOG_ROWS, _ENUMS_SQL
    intro, db = _intro()
    await intro.tables()
    assert (_ENUMS_SQL, (), _CATALOG_ROWS) in db.seen


async def test_every_catalog_query_is_read_at_the_catalog_row_cap():
    """Not just enums: 200 columns is twenty ordinary tables, and a column past
    the user-facing cap simply vanished from describe_table/ERD/search."""
    from pgllens.database.introspect import _CATALOG_ROWS
    intro, db = _intro()
    await intro.tables()
    assert len(db.seen) == 5
    assert all(max_rows == _CATALOG_ROWS for _sql, _params, max_rows in db.seen)
    assert _CATALOG_ROWS >= 100_000


async def test_a_truncated_catalog_read_logs_a_warning(caplog):
    import logging

    truncated = QueryResult(TABLES.columns, TABLES.rows, True)
    intro = Introspector(FakeDb([truncated, COLUMNS, PKS, FKS, ENUMS]),
                         Settings(database_url=DSN, exposed_schemas="wms"))
    with caplog.at_level(logging.WARNING, logger="pgllens"):
        await intro.tables()
    assert any("schema cache truncated" in r.message for r in caplog.records)


def test_fks_sql_filters_both_ends_to_the_exposed_schemas():
    """An FK whose PARENT is unexposed must not surface: it would name that
    schema's table in get_relationships, in find_path's JOIN, and KeyError the
    ERD's node lookup."""
    from pgllens.database.introspect import _FKS_SQL
    assert "n.nspname = ANY(%s)" in _FKS_SQL
    assert "fn.nspname = ANY(%s)" in _FKS_SQL


async def test_fks_query_binds_the_exposed_schemas_for_both_ends():
    from pgllens.database.introspect import _FKS_SQL
    intro, db = _intro()
    await intro.tables()
    params = next(p for sql, p, _ in db.seen if sql == _FKS_SQL)
    assert params == (intro._settings.exposed_schemas, intro._settings.exposed_schemas)


def test_enums_sql_covers_every_schema_not_just_the_exposed_ones():
    """An exposed table may use an enum defined in an unexposed schema; labels
    are type metadata, not data, so the enum query is not schema-filtered."""
    from pgllens.database.introspect import _ENUMS_SQL
    assert "nspname = ANY(" not in _ENUMS_SQL
