"""Schema cache. Every catalog query below is lifted verbatim (or, where noted,
composed from verbatim fragments) from the TypeScript schema-loader
(TS/database/schema-loader.ts); only the caching and dataclasses are new."""

from __future__ import annotations

import asyncio
import difflib
import logging
import time
from dataclasses import dataclass, field
from typing import TypedDict, cast

from pgllens.config import Settings
from pgllens.database.format import QueryResult
from pgllens.database.pool import Db

logger = logging.getLogger("pgllens")


class TableNotFoundError(LookupError):
    """Table is not in any exposed schema."""


class FunctionNotFoundError(LookupError):
    """Function is not in the resolved schema."""


class TableDetail(TypedDict):
    """The shape erd.model.build_erd's _IntrospectorLike.describe_table returns --
    kept here (not just in erd/model.py) so the type is defined once. erd/model.py
    is unchanged from the MSSQL port; tools/erd.py adapts our Table/ForeignKey
    dataclasses into this QueryResult-based shape rather than rewriting model.py."""

    columns: QueryResult
    primary_key: QueryResult
    foreign_keys: QueryResult
    description: str | None


@dataclass
class Column:
    name: str
    data_type: str
    nullable: bool
    default: str | None
    comment: str | None
    ordinal: int
    # Namespace of the column's type (pg_type.typnamespace). format_type renders
    # a type UNQUALIFIED when its schema is on the search_path, so this is what
    # lets enum_labels resolve `status` to the right `schema.status` when two
    # schemas define one. Optional so hand-built Columns (tests, ERD adapters)
    # need not supply it.
    type_schema: str | None = None
    # pg_attribute.attidentity: '' (not an identity column), 'a' (GENERATED
    # ALWAYS AS IDENTITY), 'd' (GENERATED BY DEFAULT AS IDENTITY). Kept LAST
    # and keyworded so any positional Column(...) construction elsewhere is
    # unaffected -- erd/model.py builds its own ErdColumn, not this one.
    is_identity: str = ""


@dataclass
class Table:
    schema: str
    name: str
    kind: str            # pg_class.relkind: r, v, m, p, f
    comment: str | None
    columns: list[Column] = field(default_factory=list)
    primary_key: list[str] = field(default_factory=list)
    row_estimate: int = 0

    @property
    def qualified(self) -> str:
        return f"{self.schema}.{self.name}"


@dataclass
class ForeignKey:
    constraint: str
    from_schema: str
    from_table: str
    from_columns: list[str]
    to_schema: str
    to_table: str
    to_columns: list[str]
    # attnotnull of each from_column (same order as from_columns) -- the FK's
    # child/referencing side; empty for callers that construct ForeignKey
    # directly without it (erd/model.py's _fk_rows then falls back to nullable).
    from_not_null: list[bool] = field(default_factory=list)


# --- SQL: composed from TS/database/schema-loader.ts ---

# relkind IN (...) and the reltuples CASE are lifted verbatim from
# loadEstimatedRowCounts; obj_description(c.oid, 'pg_class') is lifted verbatim
# from loadViewDefinitions/loadTriggers. relkind is extended to cover
# view/matview/partition/foreign-table, per Table.kind's documented range.
_TABLES_SQL = """
    SELECT
      n.nspname AS table_schema,
      c.relname AS table_name,
      c.relkind AS table_kind,
      obj_description(c.oid, 'pg_class') AS table_comment,
      CASE WHEN c.reltuples < 0 THEN 0 ELSE c.reltuples::bigint END AS row_estimate
    FROM pg_class c
    JOIN pg_namespace n ON c.relnamespace = n.oid
    WHERE c.relkind IN ('r', 'v', 'm', 'p', 'f')
      AND n.nspname = ANY(%s)
    ORDER BY n.nspname, c.relname
"""

# The information_schema.columns projection is lifted verbatim from
# loadTablesAndViews's columnsQuery (the pk/fk LEFT JOINs there are dropped --
# primary keys are loaded separately below), except the type itself: joined to
# pg_attribute and read via format_type(atttypid, atttypmod) -- the same
# pattern modules.py::_VIEW_COLUMNS_SQL already uses -- because
# information_schema.columns.data_type renders every enum column as the
# literal string 'USER-DEFINED' instead of the enum's real type name.
_COLUMNS_SQL = """
    SELECT
      c.table_schema,
      c.table_name,
      c.column_name,
      format_type(a.atttypid, a.atttypmod) AS data_type,
      c.is_nullable,
      c.column_default,
      col_description((c.table_schema || '.' || c.table_name)::regclass,
                       c.ordinal_position) as column_comment,
      c.ordinal_position,
      tn.nspname AS type_schema,
      a.attidentity
    FROM information_schema.columns c
    JOIN pg_attribute a
      ON a.attrelid = (c.table_schema || '.' || c.table_name)::regclass
     AND a.attname = c.column_name
     AND NOT a.attisdropped
    JOIN pg_type t ON t.oid = a.atttypid
    JOIN pg_namespace tn ON tn.oid = t.typnamespace
    WHERE c.table_schema = ANY(%s)
    ORDER BY c.table_schema, c.table_name, c.ordinal_position
"""

# The pg_constraint/pg_class/pg_namespace/pg_attribute join is lifted verbatim
# from loadTablesAndViews's inline "pk" subquery (contype = 'p'); ordinality is
# added so composite primary keys preserve column order.
_PKS_SQL = """
    SELECT
      n.nspname AS table_schema,
      cl.relname AS table_name,
      a.attname AS column_name
    FROM pg_constraint con
    JOIN pg_class cl ON con.conrelid = cl.oid
    JOIN pg_namespace n ON cl.relnamespace = n.oid
    JOIN LATERAL unnest(con.conkey) WITH ORDINALITY AS k(attnum, ord) ON true
    JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = k.attnum
    WHERE con.contype = 'p'
      AND n.nspname = ANY(%s)
    ORDER BY n.nspname, cl.relname, k.ord
"""

# The join/unnest-with-ordinality block is lifted verbatim from
# loadTablesAndViews's inline "fk" subquery (contype = 'f'); array_agg
# aggregation (per column, ordered by the shared ordinality) is added -- the
# TS version resolved fk info per-column rather than per-constraint -- using
# the same array_agg ... ORDER BY pattern loadCheckConstraints uses. BOTH ends
# are filtered to the exposed schemas: an FK into an unexposed schema would
# otherwise name that schema's tables in get_relationships, find_path's JOIN
# and the ERD (whose node lookup then KeyErrors on the missing parent).
_FKS_SQL = """
    SELECT
      con.conname AS constraint,
      n.nspname AS from_schema,
      cl.relname AS from_table,
      array_agg(a.attname ORDER BY cols.ord) AS from_columns,
      array_agg(a.attnotnull ORDER BY cols.ord) AS from_not_null,
      fn.nspname AS to_schema,
      fcl.relname AS to_table,
      array_agg(fa.attname ORDER BY cols.ord) AS to_columns
    FROM pg_constraint con
    JOIN pg_class cl ON con.conrelid = cl.oid
    JOIN pg_namespace n ON cl.relnamespace = n.oid
    JOIN pg_class fcl ON con.confrelid = fcl.oid
    JOIN pg_namespace fn ON fcl.relnamespace = fn.oid
    CROSS JOIN LATERAL unnest(con.conkey, con.confkey)
      WITH ORDINALITY AS cols(conkey_col, confkey_col, ord)
    JOIN pg_attribute a ON a.attrelid = con.conrelid
      AND a.attnum = cols.conkey_col
    JOIN pg_attribute fa ON fa.attrelid = con.confrelid
      AND fa.attnum = cols.confkey_col
    WHERE con.contype = 'f'
      AND n.nspname = ANY(%s)
      AND fn.nspname = ANY(%s)
    GROUP BY con.conname, n.nspname, cl.relname, fn.nspname, fcl.relname
    ORDER BY n.nspname, cl.relname, con.conname
"""


# Enum labels, every schema -- an exposed table may use an enum type defined in
# an unexposed schema, and a label is type metadata, not table data, so this one
# is deliberately not filtered by EXPOSED_SCHEMAS.
_ENUMS_SQL = """
    SELECT n.nspname AS type_schema, t.typname AS type_name,
           array_agg(e.enumlabel ORDER BY e.enumsortorder) AS labels
    FROM pg_type t
    JOIN pg_enum e ON e.enumtypid = t.oid
    JOIN pg_namespace n ON t.typnamespace = n.oid
    GROUP BY n.nspname, t.typname
    ORDER BY n.nspname, t.typname
"""

# Catalog metadata rows are small and must never be silently truncated at the
# user-facing MAX_ROWS (200 by default): 200 columns is twenty ordinary tables,
# and a column past the cap simply vanishes from every tool. Sized for a large
# schema; _load logs a warning if it is ever hit.
_CATALOG_ROWS = 100_000


class Introspector:
    def __init__(self, db: Db, settings: Settings) -> None:
        self._db = db
        self._settings = settings
        self._tables: list[Table] | None = None
        self._fks: list[ForeignKey] | None = None
        self._enums: dict[str, list[str]] = {}
        self._loaded_at = 0.0
        self._lock = asyncio.Lock()

    def _stale(self) -> bool:
        age_ms = (time.monotonic() - self._loaded_at) * 1000
        return self._tables is None or age_ms > self._settings.schema_refresh_interval_ms

    async def tables(self) -> list[Table]:
        if self._stale():
            async with self._lock:
                if self._stale():          # re-check: another task may have loaded
                    await self._load()
        assert self._tables is not None
        return self._tables

    async def refresh(self) -> int:
        async with self._lock:
            await self._load()
        assert self._tables is not None
        return len(self._tables)

    async def _load(self) -> None:
        schemas = self._settings.exposed_schemas

        run = self._db.run_system
        tables_result = await run(_TABLES_SQL, (schemas,), max_rows=_CATALOG_ROWS)
        columns_result = await run(_COLUMNS_SQL, (schemas,), max_rows=_CATALOG_ROWS)
        pks_result = await run(_PKS_SQL, (schemas,), max_rows=_CATALOG_ROWS)
        fks_result = await run(_FKS_SQL, (schemas, schemas), max_rows=_CATALOG_ROWS)
        enums_result = await run(_ENUMS_SQL, (), max_rows=_CATALOG_ROWS)
        if any(r.truncated for r in (tables_result, columns_result, pks_result,
                                     fks_result, enums_result)):
            logger.warning("schema cache truncated at %d catalog rows; raise "
                           "introspect._CATALOG_ROWS", _CATALOG_ROWS)

        columns_by_table: dict[tuple[str, str], list[Column]] = {}
        for col_row in columns_result.rows:
            (schema, name, col_name, data_type, is_nullable, default, comment, ordinal,
             type_schema, is_identity) = cast(
                "tuple[str, str, str, str, str, str | None, str | None, int, str, str]",
                col_row
            )
            # information_schema.columns.is_nullable is the text 'YES'/'NO' on the
            # wire -- both are truthy strings, so bool(is_nullable) is always True.
            columns_by_table.setdefault((schema, name), []).append(
                Column(name=col_name, data_type=data_type, nullable=(is_nullable == "YES"),
                       default=default, comment=comment, ordinal=ordinal,
                       type_schema=type_schema, is_identity=is_identity)
            )

        pks_by_table: dict[tuple[str, str], list[str]] = {}
        for pk_row in pks_result.rows:
            schema, name, col_name = cast("tuple[str, str, str]", pk_row)
            pks_by_table.setdefault((schema, name), []).append(col_name)

        tables = []
        for tbl_row in tables_result.rows:
            schema, name, kind, comment, row_estimate = cast(
                "tuple[str, str, str, str | None, int]", tbl_row
            )
            key = (schema, name)
            tables.append(Table(
                schema=schema,
                name=name,
                kind=kind,
                comment=comment,
                columns=columns_by_table.get(key, []),
                primary_key=pks_by_table.get(key, []),
                row_estimate=row_estimate,
            ))

        self._tables = tables
        fks: list[ForeignKey] = []
        for fk_row in fks_result.rows:
            (constraint, from_schema, from_table, from_columns, from_not_null,
             to_schema, to_table, to_columns) = cast(
                "tuple[str, str, str, list[str], list[bool], str, str, list[str]]", fk_row
            )
            fks.append(ForeignKey(
                constraint=constraint, from_schema=from_schema,
                from_table=from_table, from_columns=list(from_columns),
                to_schema=to_schema, to_table=to_table,
                to_columns=list(to_columns),
                from_not_null=list(from_not_null),
            ))
        self._fks = fks

        # Keyed by "schema.type" always, and by the bare "type" only when the
        # name is unique across schemas -- format_type omits the schema for
        # types on the search_path, so the bare key is the common lookup; an
        # ambiguous bare name resolves to nothing rather than to a guess.
        enums: dict[str, list[str]] = {}
        bare_counts: dict[str, int] = {}
        for enum_row in enums_result.rows:
            type_schema, type_name, labels = cast(
                "tuple[str, str, list[str]]", enum_row
            )
            enums[f"{type_schema}.{type_name}"] = list(labels)
            bare_counts[type_name] = bare_counts.get(type_name, 0) + 1
            enums.setdefault(type_name, list(labels))
        for bare, count in bare_counts.items():
            if count > 1:
                enums.pop(bare, None)
        self._enums = enums
        self._loaded_at = time.monotonic()

    async def table(self, name: str, schema: str | None = None) -> Table:
        wanted = name.lower()
        if "." in wanted:
            schema, wanted = wanted.split(".", 1)
        candidates = await self.tables()
        for t in candidates:
            if t.name.lower() == wanted and (schema is None
                                             or t.schema.lower() == schema.lower()):
                return t
        if schema is not None:
            homes = sorted({t.schema for t in candidates if t.name.lower() == wanted})
            where = f"in schema {schema!r}"
            if homes:
                raise TableNotFoundError(
                    f"Table {name!r} not found {where}; it exists in {', '.join(homes)}.")
        else:
            where = "in exposed schemas"
        near = difflib.get_close_matches(wanted, [t.name for t in candidates], n=3)
        hint = f" Did you mean: {', '.join(near)}?" if near else ""
        raise TableNotFoundError(f"Table {name!r} not found {where}.{hint}")

    async def foreign_keys(self) -> list[ForeignKey]:
        # Shares _load()'s staleness clock and lock with tables() -- FKs are
        # loaded alongside tables in one round trip, so there's one cache to
        # invalidate, not two.
        if self._stale():
            async with self._lock:
                if self._stale():
                    await self._load()
        assert self._fks is not None
        return self._fks

    async def enum_labels(self, data_type: str,
                          type_schema: str | None = None) -> list[str] | None:
        """Ordered labels of the enum type a column's `format_type` string names,
        or None when it isn't an enum. Accepts qualified (`app.status`), bare
        (`status`), quoted (`"App"."Status"`) and array-of-enum (`status[]`)
        renderings. Pass the column's `type_schema` when you have it: a bare
        rendering is then qualified with it, so an enum whose name is also used
        by some other schema still resolves instead of reading as ambiguous.

        A qualified name that misses is simply not an enum -- there is no
        fall-back to the bare name, which would hand a domain or composite type
        another schema's identically-named enum's labels."""
        await self.tables()          # shares _load's staleness clock and lock
        key = data_type.strip().removesuffix("[]").strip()
        # format_type double-quotes any identifier that needs it; the cache keys
        # are raw nspname/typname. Deliberately simple: a plain split on '.', so a
        # quoted identifier that itself contains a dot ("a.b".t) doesn't resolve.
        # Parse quotes properly if anyone ever hits that.
        key = ".".join(part.strip('"') for part in key.split("."))
        if type_schema is not None and "." not in key:
            key = f"{type_schema}.{key}"
        return self._enums.get(key)

    async def search_columns(self, pattern: str) -> list[tuple[str, str, str, str]]:
        """(schema, table, column, data_type) tuples whose column name contains
        `pattern` (case-insensitive substring), across all cached tables."""
        needle = pattern.lower()
        return [
            (t.schema, t.name, c.name, c.data_type)
            for t in await self.tables()
            for c in t.columns
            if needle in c.name.lower()
        ]
